"""add post tag array field

Revision ID: 11fb1fba3e
Revises: 3fc03ecf62e
Create Date: 2015-09-05 15:14:12.542844

"""

# revision identifiers, used by Alembic.
revision = '11fb1fba3e'
down_revision = '3fc03ecf62e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=True))
    op.create_index(op.f('ix_blog_post_tags'), 'blog_post', ['tags'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_tags'), table_name='blog_post')
    op.drop_column('blog_post', 'tags')
    ### end Alembic commands ###
