"""add description field for category


Revision ID: 3b54219c648
Revises: e7f39c58ae
Create Date: 2015-10-04 18:17:29.731555

"""

# revision identifiers, used by Alembic.
revision = '3b54219c648'
down_revision = 'e7f39c58ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_category', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_category', 'description')
    ### end Alembic commands ###
