"""add excerpt field to post

Revision ID: e7f39c58ae
Revises: 11fb1fba3e
Create Date: 2015-10-04 18:11:06.697989

"""

# revision identifiers, used by Alembic.
revision = 'e7f39c58ae'
down_revision = '11fb1fba3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('excerpt', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'excerpt')
    ### end Alembic commands ###
