"""add author website to comment

Revision ID: 3fc03ecf62e
Revises: 62362116d
Create Date: 2015-09-05 14:34:23.952898

"""

# revision identifiers, used by Alembic.
revision = '3fc03ecf62e'
down_revision = '62362116d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('author_website', sa.String(length=128), nullable=True))
    op.drop_column('blog_comment', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('blog_comment', 'author_website')
    ### end Alembic commands ###
