"""nested category support

Revision ID: 523db3c1572
Revises: 2dd22cf14d8
Create Date: 2015-09-05 01:35:49.705812

"""

# revision identifiers, used by Alembic.
revision = '523db3c1572'
down_revision = '2dd22cf14d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blog_category_parent_id'), 'blog_category', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'blog_category', 'blog_category', ['parent_id'], ['id'])
    op.create_index(op.f('ix_blog_comment_post_id'), 'blog_comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_blog_post_category_id'), 'blog_post', ['category_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_category_id'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_comment_post_id'), table_name='blog_comment')
    op.drop_constraint(None, 'blog_category', type_='foreignkey')
    op.drop_index(op.f('ix_blog_category_parent_id'), table_name='blog_category')
    op.drop_column('blog_category', 'parent_id')
    ### end Alembic commands ###
