"""add category & post slug

Revision ID: 62362116d
Revises: 523db3c1572
Create Date: 2015-09-05 13:23:32.492785

"""

# revision identifiers, used by Alembic.
revision = '62362116d'
down_revision = '523db3c1572'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_category', sa.Column('slug', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_blog_category_slug'), 'blog_category', ['slug'], unique=True)
    op.add_column('blog_post', sa.Column('slug', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_blog_post_slug'), 'blog_post', ['slug'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_slug'), table_name='blog_post')
    op.drop_column('blog_post', 'slug')
    op.drop_index(op.f('ix_blog_category_slug'), table_name='blog_category')
    op.drop_column('blog_category', 'slug')
    ### end Alembic commands ###
